name: Dominate
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: pip install requests
      - name: Generate
        run: python dominate.py
        env:
          openrouter_api_key: ${{ secrets.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 }}
          AMAZON_TAG: ${{ secrets.gadgethumans-21}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Commit
        run: |
          git config user.name "AI"
          git add .
          git diff --quiet || git commit -m "Auto"
          git push
